ingress: https://arbeid.dev.nav.no/arbeid/registrering
basePath: /arbeid/registrering
mocking: disabled
nodeEnv: test
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginservice:
  url: https://loginservice.dev.nav.no/login
amplitude:
  apiKey: 9845ded64c69cd068651cd0d968e0796
  endPoint: amplitude.nav.no/collect
sentry:
  dsn: https://b2f662d8ed7a42b29f465f365e25832f@sentry.gc.nav.no/118
pamJanzzUrl: https://arbeidsplassen.dev.nav.no/pam-janzz/rest
startUrl: https://arbeid.dev.nav.no/arbeid/registrering/start
startRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerordinaerregistrering/
fullforRegistreringSykmeldtUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoersykmeldtregistrering/
reaktiveringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerreaktivering/
sisteArbeidsforholdUrl: http://veilarbregistrering/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://veilarbregistrering/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://veilarbregistrering/veilarbregistrering/api/person/kontaktinfo
ptoProxyUrl: http://pto-proxy.pto.svc.cluster.local/proxy/
dittNAVUrl: https://www.dev.nav.no/person/dittnav
dagpengesoknadUrl: https://arbeid.dev.nav.no/dagpenger/dialog/soknad
dialogUrl: https://www.dev.nav.no/arbeid/dialog
featureToggles:
  server: https://unleash.nais.io/api/client/features?tag[]=simple:arbeidssokerregistrering
  client: https://arbeid.dev.nav.no/arbeid/registrering/api/features
hentProfileringUrl: http://veilarbregistrering/veilarbregistrering/api/profilering/
