ingress: https://www.nav.no/arbeid/registrering
basePath: /arbeid/registrering
mocking: disabled
nodeEnv: production
dekorator:
  url: https://dekoratoren.nav.no/
  env: prod
amplitude:
  apiKey: 913768927b84cde5eac0d0d18c737561
  endPoint: amplitude.nav.no/collect
sentry:
  dsn: https://b2f662d8ed7a42b29f465f365e25832f@sentry.gc.nav.no/118
pamJanzzUrl: https://arbeidsplassen.nav.no/pam-janzz/rest
startUrl: https://www.nav.no/arbeid/registrering/start
startRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/startregistrering/
fullforRegistreringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerordinaerregistrering/
fullforRegistreringSykmeldtUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoersykmeldtregistrering/
reaktiveringUrl: http://veilarbregistrering/veilarbregistrering/api/fullfoerreaktivering/
sisteArbeidsforholdUrl: http://veilarbregistrering/veilarbregistrering/api/sistearbeidsforhold/
opprettOppgaveUrl: http://veilarbregistrering/veilarbregistrering/api/oppgave/
kontaktinformasjonUrl: http://veilarbregistrering/veilarbregistrering/api/person/kontaktinfo
dittNAVUrl: https://www.nav.no/minside
dagpengesoknadUrl: https://www.nav.no/dagpenger/dialog/soknad
dialogUrl: https://www.nav.no/arbeid/dialog
hentProfileringUrl: http://veilarbregistrering/veilarbregistrering/api/profilering/
unleashServerApiUrl: https://paw-unleash-api.nav.cloud.nais.io/api
arbeidssokerUrl: http://veilarbregistrering/veilarbregistrering/api/arbeidssoker/perioder/niva3
