apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "arbeidssokerregistrering"
  namespace: "paw"
  labels:
    "team": "paw"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/arbeid/registrering/api/isalive"
    initialDelay: 3
  readiness:
    path: "/arbeid/registrering/api/isready"
    initialDelay: 3
  replicas:
    min: 1
    max: 3
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  env:
    - name: SELF_URL
      value: https://www.nav.no/arbeid/registrering
    - name: DEKORATOR_URL
      value: https://dekoratoren.nav.no/
    - name: DEKORATOR_ENV
      value: prod
    - name: NEXT_PUBLIC_SELF_URL
      value: https://www.nav.no/arbeid/registrering
    - name: NEXT_PUBLIC_START_URL
      value: https://www.nav.no/arbeid/registrering/start
    - name: NEXT_PUBLIC_AMPLITUDE_API_KEY
      value: 913768927b84cde5eac0d0d18c737561
    - name: NEXT_PUBLIC_AMPLITUDE_ENDPOINT
      value: https://amplitude.nav.no/collect
    - name: NEXT_PUBLIC_ENABLE_MOCK
      value: disabled
    - name: NEXT_PUBLIC_DITTNAV_URL
      value: https://www.nav.no/minside
    - name: NEXT_PUBLIC_DAGPENGESOKNAD_URL
      value: https://www.nav.no/dagpenger/dialog/soknad
    - name: NEXT_PUBLIC_DIALOG_URL
      value: https://www.nav.no/arbeid/dialog
    - name: NEXT_PUBLIC_MER_OPPFOLGING_URL
      value: https://www.nav.no/syk/meroppfolging/reg/0
    - name: PAM_JANZZ_URL
      value: https://arbeidsplassen.nav.no/pam-janzz/rest
    - name: START_REGISTRERING_URL
      value: http://veilarbregistrering/veilarbregistrering/api/startregistrering/
    - name: FULLFOR_REGISTRERING_URL
      value: http://veilarbregistrering/veilarbregistrering/api/fullfoerordinaerregistrering/
    - name: REAKTIVERING_URL
      value: http://veilarbregistrering/veilarbregistrering/api/fullfoerreaktivering/
    - name: OPPRETT_OPPGAVE_URL
      value: http://veilarbregistrering/veilarbregistrering/api/oppgave/
    - name: KONTAKTINFORMASJON_URL
      value: http://veilarbregistrering/veilarbregistrering/api/person/kontaktinfo
    - name: NODE_ENV
      value: production
    - name: HENT_PROFILERING_URL
      value: http://veilarbregistrering/veilarbregistrering/api/profilering/
    - name: UNLEASH_SERVER_API_URL
      value: https://paw-unleash-api.nav.cloud.nais.io/api
    - name: ARBEIDSSOKER_PERIODER_URL
      value: http://veilarbregistrering/veilarbregistrering/api/arbeidssoker/perioder/niva3
    - name: OPPGAVE_API_URL
      value: http://aia-backend/aia-backend/oppgave
    - name: NEXT_PUBLIC_ASSET_PREFIX
      value: https://cdn.nav.no/paw/arbeidssokerregistrering
    - name: AAREG_REST_API
      value: https://aareg-services.prod-fss-pub.nais.io/api
    - name: AAREG_CLUSTER
      value: prod-fss
    - name: AAREG_APPNAME
      value: aareg-services-nais
    - name: INNGANG_API_URL
      value: http://paw-arbeidssokerregisteret-api-inngang
  envFrom:
     - secret: poa-arbeidssokerregistrering-unleash-api-token
  ingresses:
    - https://www.nav.no/arbeid/registrering
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
        - host: arbeidsplassen.nav.no
        - host: paw-unleash-api.nav.cloud.nais.io
        - host: aareg-services.prod-fss-pub.nais.io
      rules:
        - application: paw-arbeidssokerregisteret-api-inngang
        - application: veilarbregistrering
        - application: aia-backend
        - application: nav-dekoratoren
          namespace: personbruker
        - application: aareg-services-nais
          namespace: arbeidsforhold
          cluster: prod-fss
