apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: poa-arbeidssokerregistrering-unleash
  namespace: paw
  labels:
    "team": "paw"
spec:
    unleashInstance:
      apiVersion: unleash.nais.io/v1
      kind: RemoteUnleash
      name: paw
    secretName: poa-arbeidssokerregistrering-unleash-api-token
    environment: production